
service: python-s3-thumbnail-a

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  profile: serverless-admin
  memorySize: 128
  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "s3:*"
     Resource: "*"
  environment:
     THUMBNAIL_SIZE: "128"

package:
  patterns:
    - '!node_modules/**'
    - 'node_modules/node-fetch/**'

custom:
  bucket: a-s3-thumbnail-generator

functions:
  s3-thumbnail-generator:
    handler: handler.s3_thumbnail_generator
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png

plugins:
  - serverless-python-requirements
